### ISSUE TITLE
Implements more cache bins

### ISSUE THREAD

**Issue by RoySegall** [RoySegall/rethinkdb#30]
Service example:

``` yml
  cache.backend.rethinkdb:
    class: Drupal\rethinkdb\Cache\CacheBackendFactory
    arguments: ['@rethinkdb_cache', '@cache_tags.invalidator.checksum']
```
- [ ] `$settings['cache']['default']`
